image: java:8-jdk

stages:
  - build
  
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew  

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    reports:
      junit: build/test-results/test/TEST-*.xml      
    expire_in: 1 week
  only:
    - master
      
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"