image: openjdk:8-jdk

stages:
  - build
  
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew  

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    reports:
      junit: build/test-results/test/TEST-*.xml      
    expire_in: 1 week
  only:
    - master
      
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"