image: openjdk:8

pipelines:
  default:
    - step:
        caches:
          - gradle
          - gradlewrapper
        script:
          - export GRADLE_OPTS='-Dorg.gradle.daemon=false'
          - bash ./gradlew build
        artifacts:
          - ./**/test-results/**/*.xml
          - ./**/build/libs/*.jar

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper