image: atlassianlabs/docker-node-jdk-chrome-firefox

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - export GRADLE_OPTS='-Dorg.gradle.daemon=false'
          - bash ./gradlew build