= ComicsAPI API Guide - About
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

Web Comic downloader v2.0. A rethink of the initial comic caching program. This is the API that the backend exposed for the Angular Frontend to use.

This API documentation is written using a combination of link:https://spring.io/projects/spring-restdocs[spring-restdocs-mockmvc] and link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[asciidoctor].



include::_toc.adoc[]

== Introduction
By the Martin Fowler definition of REST, this API is currently a link:https://martinfowler.com/articles/richardsonMaturityModel.html[level 2] REST API. As I've written this for the Comics Viewer, Level 3 with its discoverability hasn't been needed at this time.


== HTTP verbs
ComicsAPI adheres as closely as possible to standard HTTP and REST conventions in its use of HTTP verbs.

|===
|Verb|Usage

|GET|Used to retrieve a resource
|POST|Used to create a new resource
|PATCH|Used to update an existing resource, including partial updates
|DELETE|Used to delete an existing resource
|===

== HTTP status codes

ComicsAPI adheres as closely as possible to standard HTTP and REST conventions in its use of HTTP status codes.
|===
|Status code	|Usage

|200 OK|The request completed successfully
|201 Created|A new resource has been created successfully. The resource’s URI is available from the response’s Location header
|204 No Content|An update to an existing resource has been applied successfully
|400 Bad Request|The request was malformed. The response body will include an error providing further information
|404 Not Found|The requested resource did not exist
|===

== Authentication
TBD